i3-config: /home/jvinyals/.config/i3/config
polybar-config: /home/jvinyals/.config/polybar/config
xresources: /home/jvinyals/.Xresources
nitrogen-config: /home/jvinyals/.config/nitrogen/bg-saved.cfg
wallpaper-path: /home/jvinyals/.config/nitrogen/
